### ISSUE TITLE
Stop importing cockpit's base1/patternfly.css

### ISSUE THREAD

**Issue by martinpitt** [abbra/cockpit-app-samba-ad#2]
This is deprecated API and will be dropped at some point, in favor of projects shipping their own CSS. Please see the [deprecation announcement](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/2Q6AAQXGI5IE5D7XMTJUIKP3NIS3CIBL/) for details.

It seems that samba-ad does not use PatternFly at all, so most of the example commits don't even apply  to you. Quite possibly the only change that you need to do is to drop

    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">

**Comment by martinpitt** [comment]
I have some trouble building the package. After `npm install` and `make` (== `npm run build`), it fails with
```
/var/home/martin/tmp/cockpit-app-samba-ad/node_modules/schema-utils/dist/validate.js:96
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
[...]
```

**Comment by abbra** [comment]
@martinpitt please ignore. I need to remove this repository.

It was a prototype, not completed. The correct place now is a work being done by our GSoC student this summer at https://gitlab.com/HezekiahM/samba-ad-dc/-/tree/develop.

If you can, please provide your suggestions there. I see some patternfly uses there: https://gitlab.com/search?utf8=%E2%9C%93&search=patternfly&group_id=&project_id=19085415&scope=&search_code=true&snippets=false&repository_ref=develop&nav_source=navbar but it is based on the recent Cockpit Starter Kit code already.

**Comment by martinpitt** [comment]
@abbra: Ack, thanks for the fast feeback! I filed https://gitlab.com/HezekiahM/samba-ad-dc/-/issues/1 and close this one.
